// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDmuGSmjOsodsl9pQ4iStNFYSPPEAM4y8',
    appId: '1:702493573563:web:a288d237b0f7e259fa449e',
    messagingSenderId: '702493573563',
    projectId: 'mywork-c75e7',
    authDomain: 'mywork-c75e7.firebaseapp.com',
    storageBucket: 'mywork-c75e7.appspot.com',
    measurementId: 'G-9NZPBS3VRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4MMxzvQY7KREjAn61lNml11p3nOYwpg',
    appId: '1:702493573563:android:f05397b351522198fa449e',
    messagingSenderId: '702493573563',
    projectId: 'mywork-c75e7',
    storageBucket: 'mywork-c75e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYFB-Jw1Ns9s_WF4Svbqgq9h7N0nNUGA8',
    appId: '1:702493573563:ios:7cacb60549785faffa449e',
    messagingSenderId: '702493573563',
    projectId: 'mywork-c75e7',
    storageBucket: 'mywork-c75e7.appspot.com',
    androidClientId: '702493573563-824nu12vslgm9k7vih739qv6d0qaiblo.apps.googleusercontent.com',
    iosClientId: '702493573563-m5qb315088ut3qvta4cekirvekqvfft7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWork',
  );
}
